"""
Django settings for creator_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-change-me',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

CONFIGURED_ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
ALLOWED_HOSTS = CONFIGURED_ALLOWED_HOSTS or (
    ['localhost', '127.0.0.1', '[::1]', 'testserver'] if DEBUG else []
)


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.ApiLoginRequiredMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'creator_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'creator_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DB_ENGINE', '').lower() in {'postgres', 'postgresql'}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'creator'),
            'USER': os.environ.get('DB_USER', 'creator'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Payroll and form automation uploads can contain several screenshots,
# spreadsheets, PDFs, and invoice files. Keep this aligned with Nginx
# client_max_body_size.
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FILES = int(os.environ.get('DATA_UPLOAD_MAX_NUMBER_FILES', '500'))

# SimpleUI admin branding (admin language follows LANGUAGE_CODE above).
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_HOME_ACTION = False
SIMPLEUI_LOGO = '/static/core/admin/creator-logo.jpg'
SIMPLEUI_DEFAULT_THEME = 'creator.css'
SIMPLEUI_HOME_PAGE = '/admin/auth/user/'
SIMPLEUI_HOME_TITLE = '用户资料'
SIMPLEUI_HOME_ICON = 'far fa-id-card'
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['用户信息管理', '任务管理', '直播监控管理', '卫士软件管理', '安全管理'],
    'menus': [
        {
            'name': '用户信息管理',
            'icon': 'fas fa-users',
            'models': [
                {'name': '用户资料', 'icon': 'far fa-id-card', 'url': '/admin/auth/user/'},
                {'name': '权限组', 'icon': 'fas fa-user-shield', 'url': '/admin/auth/group/'},
            ],
        },
        {
            'name': '任务管理',
            'icon': 'fas fa-list-check',
            'models': [
                {'name': '薪资计算任务', 'icon': 'fas fa-wallet', 'url': '/admin/core/payrolljob/'},
                {'name': '报销与采购任务', 'icon': 'far fa-file-lines', 'url': '/admin/core/formautomationjob/'},
            ],
        },
        {
            'name': '直播监控管理',
            'icon': 'fas fa-video',
            'models': [
                {'name': '监控记录', 'icon': 'fas fa-chart-line', 'url': '/admin/core/douyinmonitorsession/'},
                {'name': '告警配置', 'icon': 'far fa-bell', 'url': '/admin/core/douyinmonitorconfig/'},
            ],
        },
        {
            'name': '卫士软件管理',
            'icon': 'fas fa-key',
            'models': [
                {'name': '授权管理', 'icon': 'fas fa-laptop-code', 'url': '/admin/core/guardlicense/'},
            ],
        },
        {
            'name': '安全管理',
            'icon': 'fas fa-shield-halved',
            'models': [
                {'name': '用户安全日志', 'icon': 'fas fa-clock-rotate-left', 'url': '/admin/core/usersecurityevent/'},
            ],
        },
    ],
}

# Authentication and account recovery
AUTH_REQUIRE_LOGIN = env_bool('AUTH_REQUIRE_LOGIN', True)
LOGIN_URL = '/login'
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_FAILURE_VIEW = 'core.auth_views.csrf_failure'
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', '3600'))
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', '').strip()

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', '造物者 <no-reply@creatorlive.online>')

VERIFICATION_CODE_EXPIRE_MINUTES = int(os.environ.get('VERIFICATION_CODE_EXPIRE_MINUTES', '10'))
VERIFICATION_CODE_COOLDOWN_SECONDS = int(os.environ.get('VERIFICATION_CODE_COOLDOWN_SECONDS', '60'))
VERIFICATION_CODE_MAX_ATTEMPTS = int(os.environ.get('VERIFICATION_CODE_MAX_ATTEMPTS', '5'))
VERIFICATION_CODE_DAILY_LIMIT = int(os.environ.get('VERIFICATION_CODE_DAILY_LIMIT', '10'))

# Enable these only after the production HTTPS certificate is active.
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', False)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SECURE_COOKIES', False)
CSRF_COOKIE_SECURE = env_bool('DJANGO_SECURE_COOKIES', False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', False)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'http://127.0.0.1:5173',
        'http://localhost:5173',
    ])

# django-simpleui removes Django's built-in frame middleware; the custom
# SecurityHeadersMiddleware above applies the same protection.
SILENCED_SYSTEM_CHECKS = ['security.W002']
