# Generated by Django 6.0.6 on 2026-07-07 02:38

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(default='general', max_length=40)),
                ('week_start', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('host_schedule', models.FileField(upload_to=core.models.payroll_host_schedule_path)),
                ('controller_schedule', models.FileField(upload_to=core.models.payroll_controller_schedule_path)),
                ('trial_schedule', models.FileField(upload_to=core.models.payroll_trial_schedule_path)),
                ('host_data', models.FileField(upload_to=core.models.payroll_host_data_path)),
                ('result_file', models.FileField(blank=True, upload_to=core.models.payroll_output_path)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
