# Generated by Django 6.0.6 on 2026-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payrolljob'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolljob',
            name='week_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
