# Generated by Django 6.0.6 on 2026-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_formautomationjob_formautomationasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolljob',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
