# Generated by Django 6.0.6 on 2026-07-22 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_worker_job_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DouyinMonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douyin_id', models.CharField(max_length=120, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('greater', 'Greater than'), ('less', 'Less than'), ('range', 'Range')], default='greater', max_length=20)),
                ('threshold', models.PositiveIntegerField(default=100)),
                ('min_count', models.PositiveIntegerField(default=50)),
                ('max_count', models.PositiveIntegerField(default=100)),
                ('cooldown_enabled', models.BooleanField(default=False)),
                ('cooldown_minutes', models.PositiveIntegerField(default=10)),
                ('webhook', models.TextField(blank=True)),
                ('secret', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DouyinMonitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('douyin_id', models.CharField(max_length=120)),
                ('room_title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('resolving', 'Resolving'), ('connecting', 'Connecting'), ('monitoring', 'Monitoring'), ('warning', 'Warning'), ('error', 'Error'), ('stopped', 'Stopped')], default='starting', max_length=20)),
                ('status_message', models.CharField(default='正在建立独立匿名连接', max_length=300)),
                ('current_count', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=300)),
                ('sec_uid', models.CharField(blank=True, max_length=200)),
                ('room_id', models.CharField(blank=True, max_length=80)),
                ('web_rid', models.CharField(blank=True, max_length=80)),
                ('stream_url', models.TextField(blank=True)),
                ('points', models.JSONField(blank=True, default=list)),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_alert_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='douyin_status_started_idx')],
            },
        ),
    ]
