# Generated by Django 6.0.6 on 2026-07-27 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_records_to_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    admin_user = User.objects.filter(is_superuser=True).order_by('date_joined').first()
    if admin_user is None:
        return
    for model_name in ('PayrollJob', 'FormAutomationJob', 'DouyinMonitorConfig', 'DouyinMonitorSession'):
        apps.get_model('core', model_name).objects.filter(owner__isnull=True).update(owner=admin_user)


def clear_migrated_owners(apps, schema_editor):
    for model_name in ('PayrollJob', 'FormAutomationJob', 'DouyinMonitorConfig', 'DouyinMonitorSession'):
        apps.get_model('core', model_name).objects.update(owner=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_douyinmonitorconfig_douyinmonitorsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('event', models.CharField(choices=[('registered', 'Registered'), ('login_succeeded', 'Login succeeded'), ('login_failed', 'Login failed'), ('login_blocked', 'Login blocked'), ('logged_out', 'Logged out'), ('account_recovery', 'Account recovery requested'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed')], max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='douyinmonitorconfig',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='douyin_monitor_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='douyinmonitorsession',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='douyin_monitor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formautomationjob',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_automation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolljob',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_existing_records_to_admin, clear_migrated_owners),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='douyin_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='douyinmonitorconfig',
            constraint=models.UniqueConstraint(fields=('owner', 'douyin_id'), name='douyin_owner_id_unique'),
        ),
        migrations.AddField(
            model_name='usersecurityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersecurityevent',
            index=models.Index(fields=['event', 'username', 'created_at'], name='security_event_user_idx'),
        ),
        migrations.AddIndex(
            model_name='usersecurityevent',
            index=models.Index(fields=['ip_address', 'created_at'], name='security_event_ip_idx'),
        ),
    ]
