# Generated by Django 6.0.6 on 2026-07-27 09:44

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_accounts_and_task_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='douyinmonitorconfig',
            options={'verbose_name': '直播告警配置', 'verbose_name_plural': '直播告警配置'},
        ),
        migrations.AlterModelOptions(
            name='douyinmonitorsession',
            options={'ordering': ['-started_at'], 'verbose_name': '直播监控记录', 'verbose_name_plural': '直播监控记录'},
        ),
        migrations.AlterModelOptions(
            name='formautomationasset',
            options={'ordering': ['group', 'original_name'], 'verbose_name': '任务文件', 'verbose_name_plural': '任务文件'},
        ),
        migrations.AlterModelOptions(
            name='formautomationjob',
            options={'ordering': ['-created_at'], 'verbose_name': '报销与采购任务', 'verbose_name_plural': '报销与采购任务'},
        ),
        migrations.AlterModelOptions(
            name='payrolljob',
            options={'ordering': ['-created_at'], 'verbose_name': '薪资计算任务', 'verbose_name_plural': '薪资计算任务'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.AlterModelOptions(
            name='usersecurityevent',
            options={'ordering': ['-created_at'], 'verbose_name': '用户安全日志', 'verbose_name_plural': '用户安全日志'},
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='cooldown_enabled',
            field=models.BooleanField(default=False, verbose_name='启用告警冷却'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='冷却时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='douyin_id',
            field=models.CharField(max_length=120, verbose_name='抖音号'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='启用告警'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='max_count',
            field=models.PositiveIntegerField(default=100, verbose_name='最大人数'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='min_count',
            field=models.PositiveIntegerField(default=50, verbose_name='最小人数'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='mode',
            field=models.CharField(choices=[('greater', '高于阈值'), ('less', '低于阈值'), ('range', '指定范围')], default='greater', max_length=20, verbose_name='告警规则'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='douyin_monitor_configs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='secret',
            field=models.TextField(blank=True, verbose_name='飞书签名密钥'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='threshold',
            field=models.PositiveIntegerField(default=100, verbose_name='人数阈值'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorconfig',
            name='webhook',
            field=models.TextField(blank=True, verbose_name='飞书 Webhook'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='alerts',
            field=models.JSONField(blank=True, default=list, verbose_name='告警记录'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='本次监控配置'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='current_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='当前在线人数'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='douyin_id',
            field=models.CharField(max_length=120, verbose_name='抖音号'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='end_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='结束原因'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束监控时间'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='监控 ID'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='last_alert_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后告警时间'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='douyin_monitor_sessions', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='points',
            field=models.JSONField(blank=True, default=list, verbose_name='在线人数曲线数据'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='room_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='直播间 ID'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='room_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='直播间名称'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='sec_uid',
            field=models.CharField(blank=True, max_length=200, verbose_name='抖音 SecUID'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始监控时间'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='status',
            field=models.CharField(choices=[('starting', '正在启动'), ('resolving', '正在解析直播间'), ('connecting', '正在连接'), ('monitoring', '监控中'), ('warning', '告警中'), ('error', '异常'), ('stopped', '已停止')], default='starting', max_length=20, verbose_name='监控状态'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='status_message',
            field=models.CharField(default='正在建立独立匿名连接', max_length=300, verbose_name='状态说明'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='stream_url',
            field=models.TextField(blank=True, verbose_name='直播流地址'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='douyinmonitorsession',
            name='web_rid',
            field=models.CharField(blank=True, max_length=80, verbose_name='直播间 Web RID'),
        ),
        migrations.AlterField(
            model_name='formautomationasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='formautomationasset',
            name='file',
            field=models.FileField(upload_to=core.models.form_asset_path, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='formautomationasset',
            name='group',
            field=models.CharField(max_length=40, verbose_name='文件分组'),
        ),
        migrations.AlterField(
            model_name='formautomationasset',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.formautomationjob', verbose_name='所属任务'),
        ),
        migrations.AlterField(
            model_name='formautomationasset',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='formautomationasset',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='文件大小（字节）'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='处理次数'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='claim_token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='领取令牌'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='失败原因'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='form_type',
            field=models.CharField(choices=[('expense', '费用报销表'), ('procurement', '采购申请表')], max_length=30, verbose_name='表格类型'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任务 ID'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务租约到期时间'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_automation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='处理进度（%）'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='progress_message',
            field=models.CharField(default='等待 Worker 处理', max_length=200, verbose_name='进度说明'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='result_file',
            field=models.FileField(blank=True, upload_to=core.models.form_output_path, verbose_name='结果文件'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='status',
            field=models.CharField(choices=[('pending', '等待处理'), ('running', '正在处理'), ('success', '处理成功'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='处理摘要'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='formautomationjob',
            name='worker_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Worker ID'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='处理次数'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='claim_token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='领取令牌'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='controller_schedule',
            field=models.FileField(upload_to=core.models.payroll_controller_schedule_path, verbose_name='中控排班表'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='失败原因'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='host_data',
            field=models.FileField(upload_to=core.models.payroll_host_data_path, verbose_name='主播数据'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='host_schedule',
            field=models.FileField(upload_to=core.models.payroll_host_schedule_path, verbose_name='主播排班表'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任务 ID'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务租约到期时间'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_jobs', to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='处理进度（%）'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='progress_message',
            field=models.CharField(default='等待 Worker 处理', max_length=200, verbose_name='进度说明'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='result_file',
            field=models.FileField(blank=True, upload_to=core.models.payroll_output_path, verbose_name='结果文件'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='room_type',
            field=models.CharField(default='general', max_length=40, verbose_name='直播间类型'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='status',
            field=models.CharField(choices=[('pending', '等待处理'), ('running', '正在处理'), ('success', '处理成功'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='处理摘要'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='trial_schedule',
            field=models.FileField(upload_to=core.models.payroll_trial_schedule_path, verbose_name='试播排班表'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='week_end',
            field=models.DateField(blank=True, null=True, verbose_name='周期结束日期'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='week_start',
            field=models.DateField(blank=True, null=True, verbose_name='周期开始日期'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='worker_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Worker ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='usersecurityevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发生时间'),
        ),
        migrations.AlterField(
            model_name='usersecurityevent',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='详细信息'),
        ),
        migrations.AlterField(
            model_name='usersecurityevent',
            name='event',
            field=models.CharField(choices=[('registered', '注册成功'), ('login_succeeded', '登录成功'), ('login_failed', '登录失败'), ('login_blocked', '登录已限制'), ('logged_out', '退出登录'), ('account_recovery', '申请找回账号'), ('password_reset_requested', '申请重置密码'), ('password_reset_completed', '密码重置完成')], max_length=40, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='usersecurityevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='usersecurityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='usersecurityevent',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='账号'),
        ),
    ]
