# Generated by Django 6.0.6 on 2026-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_douyinmonitorconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formautomationjob',
            name='worker_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='处理节点'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='room_type',
            field=models.CharField(choices=[('general', '通用直播间'), ('z4-neck', 'Z4 颈膜直播间'), ('z2-eye', 'Z2 眼膜直播间'), ('z3-polish', 'Z3 抛光直播间')], default='general', max_length=40, verbose_name='直播间类型'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='worker_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='处理节点'),
        ),
    ]
