# Generated by Django 6.0.6 on 2026-07-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_formautomationjob_worker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersecurityevent',
            name='event',
            field=models.CharField(choices=[('registered', '注册成功'), ('login_succeeded', '登录成功'), ('login_failed', '登录失败'), ('login_blocked', '登录已限制'), ('logged_out', '退出登录'), ('account_recovery', '申请找回账号'), ('password_reset_requested', '申请重置密码'), ('password_reset_completed', '密码重置完成'), ('verification_code_sent', '发送验证码')], max_length=40, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', '邮箱')], max_length=10, verbose_name='发送方式')),
                ('purpose', models.CharField(choices=[('account_recovery', '找回用户名'), ('password_reset', '重置密码')], max_length=30, verbose_name='使用场景')),
                ('destination', models.CharField(db_index=True, max_length=254, verbose_name='接收地址')),
                ('code_hash', models.CharField(max_length=128, verbose_name='验证码摘要')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='申请 IP')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='错误次数')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '验证码记录',
                'verbose_name_plural': '验证码记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'purpose', 'destination', 'created_at'], name='verify_code_lookup_idx')],
            },
        ),
    ]
