# Generated by Django 6.0.6 on 2026-08-01 09:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_phone_number_alter_usersecurityevent_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolljob',
            name='rating_update',
            field=models.FileField(blank=True, upload_to=core.models.payroll_rating_update_path, verbose_name='兼职评级更新'),
        ),
        migrations.AddField(
            model_name='payrolljob',
            name='schedule_image',
            field=models.FileField(blank=True, upload_to=core.models.payroll_schedule_image_path, verbose_name='综合排班表图片'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='controller_schedule',
            field=models.FileField(blank=True, upload_to=core.models.payroll_controller_schedule_path, verbose_name='场控排班表（旧版）'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='host_data',
            field=models.FileField(upload_to=core.models.payroll_host_data_path, verbose_name='兼职主播数据表'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='host_schedule',
            field=models.FileField(blank=True, upload_to=core.models.payroll_host_schedule_path, verbose_name='主播排班表（旧版）'),
        ),
        migrations.AlterField(
            model_name='payrolljob',
            name='trial_schedule',
            field=models.FileField(blank=True, upload_to=core.models.payroll_trial_schedule_path, verbose_name='试播排班表（旧版）'),
        ),
    ]
