# Generated by Django 6.0.6 on 2026-09-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_guard_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolljob',
            name='room_type',
            field=models.CharField(choices=[('general', '通用直播间'), ('z4-neck', 'Z4 颈膜直播间'), ('z2-eye', 'Z2 眼膜直播间'), ('z3-polish', 'Z3 抛光直播间'), ('z5-mud', 'Z5 泥膜直播间')], default='general', max_length=40, verbose_name='直播间类型'),
        ),
    ]
