# Generated by Django 6.0.6 on 2026-09-09 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payroll_z5_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '知识条目',
                'verbose_name_plural': '知识条目',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='分类名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序（小的在前）')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.knowledgecategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '知识分类',
                'verbose_name_plural': '知识分类',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='教程标题')),
                ('summary', models.TextField(max_length=1000, verbose_name='简要答案')),
                ('steps', models.TextField(help_text='每行一个步骤，审核发布时必须有 3～5 步。', verbose_name='快速处理步骤')),
                ('body', models.TextField(help_text='填写网站内完整教程，用空行分段；正文按纯文本展示。', verbose_name='完整教程')),
                ('platform', models.CharField(choices=[('all', '通用'), ('douyin', '抖音'), ('channels', '视频号'), ('redbook', '小红书'), ('tmall', '天猫'), ('kuaishou', '快手'), ('pdd', '拼多多')], default='all', max_length=20, verbose_name='适用平台')),
                ('keywords', models.TextField(blank=True, help_text='每行一个词组或问法，如：麦克风没声音。', verbose_name='搜索关键词 / 常见问法')),
                ('featured', models.BooleanField(default=False, verbose_name='列入常见问题')),
                ('tool_path', models.CharField(blank=True, choices=[('', '无'), ('/features', '工具库'), ('/features/live-monitor', '直播监控')], max_length=80, verbose_name='相关工具')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('returned', '已退回'), ('archived', '历史版本'), ('disabled', '已停用')], default='draft', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核意见')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.knowledgearticle', verbose_name='知识条目')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='编写人员')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.knowledgecategory', verbose_name='知识分类')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
            ],
            options={
                'verbose_name': '教程与审核',
                'verbose_name_plural': '教程与审核',
                'ordering': ('-updated_at',),
                'permissions': [('review_knowledge', '审核、发布及停用知识内容')],
            },
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.knowledgerevision', verbose_name='当前发布版本'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerevision',
            constraint=models.UniqueConstraint(fields=('article', 'version'), name='knowledge_unique_version'),
        ),
    ]
