# Generated by Django 6.0.6 on 2026-10-01 09:47

import core.knowledge_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_knowledgeconversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeQuestionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.knowledge_models.knowledge_question_asset_path, verbose_name='数据源文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='文件类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.knowledgequestionjob', verbose_name='所属问答任务')),
            ],
            options={
                'verbose_name': '知识问答数据源',
                'verbose_name_plural': '知识问答数据源',
                'ordering': ['id'],
            },
        ),
    ]
